version: '2'

services:
  # Nginx
  nginx:
    image: nginx:1.15.8-alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /var/run/docker.sock:/var/run/docker.sock
    tty: true
    ports:
      - "80:80"
    links:
      - server

  # オンラインコンパイラ
  server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile

  # オンラインコンパイラ用コンテナ
  compiler_default:
    container_name: compiler_default
    build:
      context: .
      dockerfile: ./docker/compiler_default/Dockerfile
  compiler_swift:
    container_name: compiler_swift
    build:
      context: .
      dockerfile: ./docker/compiler_swift/Dockerfile
  compiler_jvm_php:
    container_name: compiler_jvm_php
    build:
      context: .
      dockerfile: ./docker/compiler_jvm_php/Dockerfile
